# Lab-1 : Linear Algebra

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
print(arr[0])
print(arr[3])

1
4


In [6]:
print(arr.shape)
print(arr.size)

(6,)
6


In [16]:
A= np.array([[1, 2, 3],
            [3, 4, 5],
            [9, 4, 3]])
print(A)
print(A[0, 2])
print(A[2])
print(A[:1])

[[1 2 3]
 [3 4 5]
 [9 4 3]]
3
[9 4 3]
[[1 2 3]]


In [12]:
print(A.shape)
print(A.size)
print(type(A))

(3, 3)
9
<class 'numpy.ndarray'>


In [19]:
Ten = np.array([[[3, 2, 3, 4, 3], [3, 4, 3, 3, 4, 5]], [[ 3, 4, 5, 3, 4], [4, 3, 2, 3, 4]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

In [24]:
a2 = arr.copy()
print(arr+a2)
print(arr*a2)
print(np.add(arr, a2), np.divide(arr, a2), np.multiply(arr, a2))

[ 2  4  6  8 10 12]
[ 1  4  9 16 25 36]
[ 2  4  6  8 10 12] [1. 1. 1. 1. 1. 1.] [ 1  4  9 16 25 36]


In [29]:
print(np.max(arr))
print(A.T)
B = A.copy()
np.dot(A, B)

6
[[1 3 9]
 [2 4 4]
 [3 5 3]]


array([[34, 22, 22],
       [60, 42, 44],
       [48, 46, 56]])

In [33]:
from numpy.linalg import eigh, svd

In [32]:
vals, vect = eigh(A)
print(vals, vect)

[-7.07463967  1.44112869 13.63351098] [[ 0.73618174  0.34012164 -0.58511   ]
 [ 0.04449212 -0.88699675 -0.45962725]
 [-0.67531985  0.31233641 -0.66812354]]


In [35]:
U, S, VT = svd(A)
print(U)

[[-0.25260627 -0.48588279 -0.83672456]
 [-0.52701887 -0.65613844  0.54012356]
 [-0.81144389  0.57740823 -0.09032471]]


In [36]:
print(S)

[12.31925019  4.26765984  0.1521654 ]


In [37]:
print(VT)

[[-0.74165698 -0.47560229 -0.47301944]
 [ 0.64259478 -0.30149695 -0.70439445]
 [-0.19239769  0.82637888 -0.52922687]]
